### ISSUE TITLE
Add a Settings Screen to the Tip Calculator

### ISSUE THREAD

**Issue by IsaSam** [IsaSam/tipCalculator#1]
Settings page to change the default tip percentage.

**Comment by IsaSam** [comment]
Settings added

**Comment by codepathreview** [comment]
:+1 nice work. 
* Glad to see a user can enter a bill amount to see a tip value based off a percentage of the bill;
* Nice to see  user can select between 3 tip percentages by tapping different values on the segmented control and the tip value is updated accordingly
* Glad to see you are starting your setting screen 
/cc @codepathreview
